name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python (optional, if needed for your tools)
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Run semantic release
        id: release
        uses: python-semantic-release/python-semantic-release@v10.3.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          git_committer_name: "github-actions"
          git_committer_email: "actions@users.noreply.github.com"

      - name: Publish release assets
        if: steps.release.outputs.released == 'true'
        uses: python-semantic-release/publish-action@v10.3.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.release.outputs.tag }}

      - name: Sync main to dev
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git fetch origin dev
          git checkout dev
          git merge origin/main --no-edit || echo "No changes to merge"
          git push origin dev